// Curated popular channels - TV besar dari berbagai negara
export const POPULAR_CHANNELS: Record<string, string[]> = {
  // === AMERIKA ===
  US: [
    'BBC America',
    'ABC News',
    'CBS News',
    'NBC News',
    'Fox News',
    'CNN',
    'MSNBC',
    'ESPN',
    'Fox Sports',
    'NBA TV',
    'MLB Network',
    'HBO',
    'Showtime',
    'Starz',
    'AMC',
    'FX',
    'Comedy Central',
    'Nickelodeon',
    'Cartoon Network',
    'Disney Channel',
    'Discovery',
    'National Geographic',
    'History',
    'A&E',
    'TNT',
    'TBS',
    'USA Network',
    'Hallmark',
    'Paramount',
    'Cinemax',
    'BET',
    'VH1',
    'MTV',
    'Food Network',
    'HGTV',
    'Travel Channel',
    'Animal Planet',
    'Science',
    'TLC',
    'ID',
    'WE TV',
    'Oxygen',
    'BBC World News',
    'France 24 English',
    'Al Jazeera English',
    'TRT World',
    'CGTN',
    'Arirang',
    'TV5Monde',
    'DW English',
    'NHK World',
  ],
  GB: [
    'BBC One',
    'BBC Two',
    'BBC Four',
    'BBC News',
    'BBC World News',
    'ITV',
    'Channel 4',
    'Channel 5',
    'Sky News',
    'Sky Sports',
    'Sky Sports News',
    'BT Sport',
    'Eurosport',
    'Premier Sports',
    'S4C',
    'BBC Alba',
    'RTÉ',
    'Virgin Media',
    'TalkSport',
    'EuroNews',
  ],
  // === EROPA ===
  FR: [
    'France 24',
    'France 24 English',
    'France 2',
    'France 3',
    'France 5',
    'M6',
    'TF1',
    'Canal+',
    'Arte',
    'Euronews',
    'TV5Monde',
    'LCI',
    'BFM TV',
    'CNews',
    'L Equipe',
    'Gulli',
  ],
  DE: [
    'Das Erste',
    'ZDF',
    'ARD',
    'RTL',
    'ProSieben',
    'Sat.1',
    'VOX',
    'NTV',
    'N24',
    'DW English',
    'DW Deutsch',
    'EuroNews',
    'Euronews',
    'BBC World News',
    'Al Jazeera English',
    'France 24 English',
  ],
  IT: [
    'RAI 1',
    'RAI 2',
    'RAI 3',
    'RAI News',
    'Mediaset',
    'Canale 5',
    'Italia 1',
    'Rete 4',
    'La7',
    'Sky TG24',
    'Euronews',
  ],
  ES: [
    'Telecinco',
    'Antena 3',
    'La Sexta',
    'TVE',
    'TVE 24H',
    'Canal+',
    'Movistar',
    'Euronews',
    'France 24 English',
    'BBC World News',
  ],
  PT: [
    'RTP',
    'RTP 1',
    'RTP 2',
    'RTP 3',
    'SIC',
    'TVI',
    'CMTV',
    'Euronews',
  ],
  NL: [
    'NPO 1',
    'NPO 2',
    'NPO 3',
    'RTL',
    'RTL 4',
    'SBS',
    'Fox Sports',
    'Euronews',
    'BBC World News',
  ],
  // === ASIA ===
  JP: [
    'NHK',
    'NHK World',
    'NHK Educational',
    'TBS',
    'Fuji TV',
    'TV Asahi',
    'TV Tokyo',
    'Nippon TV',
    'Bloomberg',
    'Anime',
  ],
  KR: [
    'KBS',
    'KBS World',
    'MBC',
    'SBS',
    'Arirang',
    'Yonhap',
    'TV Chosun',
    'MBN',
    'Channel A',
    'JTBC',
  ],
  CN: [
    'CCTV',
    'CCTV-4',
    'CCTV-News',
    'CGTN',
    'CGTN Arabic',
    'CGTN Francais',
    'Phoenix',
    'NTDTV',
    'HRT',
  ],
  HK: [
    'TVB',
    'TVB News',
    'Now TV',
    'RTHK',
    'ViuTV',
    'Cable TV',
    'Phoenix',
    'CTI',
  ],
  TW: [
    'TTV',
    'CTV',
    'SET Taiwan',
    'TVBS',
    'FTV',
    'EBC',
    'CNA',
    'Bloomberg',
  ],
  TH: [
    'Thai TV',
    'CH3',
    'MCOT',
    'NBT',
    'TNN',
    'Spring News',
    'PPT',
    'Thairath',
    'Workpoint',
    'GMM',
  ],
  ID: [
    'TVRI',
    'RCTI',
    'SCTV',
    'Indosiar',
    'MNCTV',
    'TRANS TV',
    'TRANSMEDIA',
    'ANTV',
    'NET TV',
    'Metro TV',
    'tvOne',
    'Kompas TV',
    'CNN Indonesia',
    'CNBC Indonesia',
    'MNC News',
    'iNews',
    'RTV',
    'GTV',
    'Moji',
    'Baraya',
    'Jaktv',
    'DAAI',
    'Adi TV',
    'Jawa Pos',
    'Magna TV',
    'Channel 9',
    'TV9',
    'Sinar TV',
    'Citra TV',
    'Star TV',
    'Indonesia Travel',
    'Jakarta Globe',
  ],
  MY: [
    'RTM',
    'TV3',
    'Astro',
    'Astro Arena',
    'Astro Citra',
    'TV9',
    'Bernama',
    'Astro SuperSport',
  ],
  SG: [
    'Mediacorp',
    'Channel 5',
    'Channel 8',
    'Channel U',
    'Suria',
    'Vasantham',
    ' CNA',
    'CNA International',
    'Channel NewsAsia',
    'Bloomberg',
  ],
  PH: [
    'ABS-CBN',
    'GMA',
    'GMA News',
    'TV5',
    'CNN Philippines',
    'BBC World News',
    'Al Jazeera English',
    'ANC',
  ],
  VN: [
    'VTV',
    'VTV1',
    'VTV2',
    'VTV3',
    'VTV4',
    'VTV5',
    'VTV6',
    'HTV',
    'VTC',
    'K+',
  ],
  IN: [
    'DD National',
    'DD News',
    'NDTV',
    'NDTV India',
    'Aaj Tak',
    'India TV',
    'Zee News',
    'Aapka',
    'Republic Bharat',
    'Times Now',
    'CNN News18',
    'CNBC TV18',
    'ABP News',
    'Zee TV',
    'Star Plus',
    'Sony',
    'Sony ESPN',
    'Sports18',
    'Star Sports',
    'JioCinema',
    'Eros',
  ],
  PK: [
    'PTV',
    'PTV News',
    'Geo',
    'ARY',
    'Dawn',
    'Hum',
    'Express',
    'Aaj',
    ' Sama',
  ],
  // === MIDDLE EAST ===
  AE: [
    'Al Jazeera',
    'Al Jazeera English',
    'Al Jazeera Arabic',
    'Al Arabiya',
    'Sky News Arabia',
    'MBC',
    'Abu Dhabi',
    'Abu Dhabi Sports',
    'Dubai',
    'France 24 Arabic',
    'TRT Arabic',
  ],
  SA: [
    'Al Arabia',
    'Al Hadath',
    'MBC',
    'Rotana',
    'Saudi',
    'Saudi Sports',
    'Al Quran',
    'Saudi News',
  ],
  TR: [
    'TRT',
    'TRT World',
    'TRT Arabic',
    'TRT Haber',
    'NTV',
    'CNN Turk',
    'A Haber',
    'Show TV',
    'Star',
    'Kanal D',
    'EuroNews',
  ],
  // === AFRIKA ===
  ZA: [
    'SABC',
    'e.tv',
    'SABC News',
    'SuperSport',
    'Mzansi',
    'Mzansi Magic',
    'BBC World News',
    'Al Jazeera English',
    'France 24 English',
  ],
  NG: [
    'NTA',
    'AIT',
    'Channels',
    'TVC',
    'Nigerian News',
    'BBC World News',
    'Al Jazeera English',
  ],
  // === OCEANIA ===
  AU: [
    'ABC',
    'SBS',
    'SBS VICELAND',
    'Seven',
    'Nine',
    'Ten',
    'Sky News',
    'Fox FM',
    'ABC News',
    'BBC World News',
    'Al Jazeera English',
  ],
  NZ: [
    'TVNZ',
    'TVNZ 1',
    'TVNZ 2',
    ' Maori TV',
    'Parliament',
    'BBC World News',
    'Al Jazeera English',
  ],
  // === Sports Premium ===
  SPORTS: [
    'ESPN',
    'ESPN 2',
    'ESPN 3',
    'ESPN Brasil',
    'ESPN Latin',
    'Fox Sports',
    'Fox Sports 2',
    'Fox Sports 3',
    'Sky Sports',
    'Sky Sports News',
    'Sky Sports Premier League',
    'Sky Sports F1',
    'BT Sport',
    'BT Sport 1',
    'BT Sport 2',
    'beIN Sports',
    'beIN SPORTS',
    'beIN Sports 1',
    'beIN Sports 2',
    'beIN Sports 3',
    'Premier Sports',
    'Eurosport',
    'Eurosport 2',
    'Arena',
    'SportTV',
    'NBA TV',
    'MLB Network',
    'NFL',
    'NHL',
    'CBS Sports',
    'NBC Sports',
    'TNT Sports',
    'Astro SuperSport',
    'Star Sports',
    'Sony Ten',
    'Jio Sports',
  ],
  // === News Premium ===
  NEWS: [
    'BBC News',
    'BBC World News',
    'CNN',
    'CNN International',
    'CNBC',
    'Fox News',
    'Al Jazeera',
    'Al Jazeera English',
    'Sky News',
    'France 24',
    'France 24 English',
    'TRT World',
    'CGTN',
    'NHK World',
    'Arirang',
    'Channel NewsAsia',
    'CNA',
    'DW',
    'DW English',
    'Euronews',
    'RT',
    'RT English',
    'ABC News',
    'CBS News',
    'NBC News',
    'NDTV',
    'Times Now',
  ],
};

// Countries with flags
export const COUNTRIES = [
  { code: 'WORLD', name: '🌍 All World', flag: '🌍' },
  { code: 'US', name: '🇺🇸 USA', flag: '🇺🇸' },
  { code: 'GB', name: '🇬🇧 UK', flag: '🇬🇧' },
  { code: 'AU', name: '🇦🇺 Australia', flag: '🇦🇺' },
  { code: 'NZ', name: '🇳🇿 New Zealand', flag: '🇳🇿' },
  { code: 'JP', name: '🇯🇵 Japan', flag: '🇯🇵' },
  { code: 'KR', name: '🇰🇷 Korea', flag: '🇰🇷' },
  { code: 'CN', name: '🇨🇳 China', flag: '🇨🇳' },
  { code: 'TW', name: '🇹🇼 Taiwan', flag: '🇹🇼' },
  { code: 'HK', name: '🇭🇰 Hong Kong', flag: '🇭🇰' },
  { code: 'TH', name: '🇹🇭 Thailand', flag: '🇹🇭' },
  { code: 'ID', name: '🇮🇩 Indonesia', flag: '🇮🇩' },
  { code: 'MY', name: '🇲🇾 Malaysia', flag: '🇲🇾' },
  { code: 'SG', name: '🇸🇬 Singapore', flag: '🇸🇬' },
  { code: 'PH', name: '🇵🇭 Philippines', flag: '🇵🇭' },
  { code: 'IN', name: '🇮🇳 India', flag: '🇮🇳' },
  { code: 'PK', name: '🇵🇰 Pakistan', flag: '🇵🇰' },
  { code: 'VN', name: '🇻🇳 Vietnam', flag: '🇻🇳' },
  { code: 'FR', name: '🇫🇷 France', flag: '🇫🇷' },
  { code: 'DE', name: '🇩🇪 Germany', flag: '🇩🇪' },
  { code: 'IT', name: '🇮🇹 Italy', flag: '🇮🇹' },
  { code: 'ES', name: '🇪🇸 Spain', flag: '🇪🇸' },
  { code: 'PT', name: '🇵🇹 Portugal', flag: '🇵🇹' },
  { code: 'NL', name: '🇳🇱 Netherlands', flag: '🇳🇱' },
  { code: 'TR', name: '🇹🇷 Turkey', flag: '🇹🇷' },
  { code: 'AE', name: '🇦🇪 UAE', flag: '🇦🇪' },
  { code: 'SA', name: '🇸🇦 Saudi', flag: '🇸🇦' },
  { code: 'ZA', name: '🇿🇦 South Africa', flag: '🇿🇦' },
  { code: 'NG', name: '🇳🇬 Nigeria', flag: '🇳🇬' },
  { code: 'BR', name: '🇧🇷 Brazil', flag: '🇧🇷' },
  { code: 'MX', name: '🇲🇽 Mexico', flag: '🇲🇽' },
  { code: 'AR', name: '🇦🇷 Argentina', flag: '🇦🇷' },
  { code: 'CA', name: '🇨🇦 Canada', flag: '🇨🇦' },
  { code: 'SPORTS', name: '⚽ Sports', flag: '⚽' },
  { code: 'NEWS', name: '📰 News', flag: '📰' },
];

// Map country codes for filtering
export const COUNTRY_MAP: Record<string, string[]> = {
  US: ['US', 'USA'],
  GB: ['GB', 'UK', 'Britain', 'England'],
  AU: ['AU', 'Australia'],
  NZ: ['NZ', 'New Zealand'],
  JP: ['JP', 'Japan'],
  KR: ['KR', 'Korea', 'South Korea'],
  CN: ['CN', 'China', 'Chinese'],
  TW: ['TW', 'Taiwan'],
  HK: ['HK', 'Hong Kong'],
  TH: ['TH', 'Thailand'],
  ID: ['ID', 'Indonesia', 'Indonesian'],
  MY: ['MY', 'Malaysia', 'Malaysian'],
  SG: ['SG', 'Singapore'],
  PH: ['PH', 'Philippines', 'Filipino'],
  IN: ['IN', 'India', 'Hindi', 'Indian'],
  PK: ['PK', 'Pakistan', 'Urdu'],
  VN: ['VN', 'Vietnam', 'Viet'],
  FR: ['FR', 'France', 'French'],
  DE: ['DE', 'Germany', 'German'],
  IT: ['IT', 'Italy', 'Italian'],
  ES: ['ES', 'Spain', 'Spanish'],
  PT: ['PT', 'Portugal', 'Portuguese'],
  NL: ['NL', 'Netherlands', 'Dutch'],
  TR: ['TR', 'Turkey', 'Turkish'],
  AE: ['AE', 'UAE', 'Dubai'],
  SA: ['SA', 'Saudi', 'Arabia'],
  ZA: ['ZA', 'South Africa'],
  NG: ['NG', 'Nigeria', 'Nigerian'],
  BR: ['BR', 'Brazil', 'Brazilian'],
  MX: ['MX', 'Mexico', 'Mexican'],
  AR: ['AR', 'Argentina'],
  CA: ['CA', 'Canada', 'Canadian'],
};